package net.emojiparty.android.popularmovies.models;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.gson.annotations.SerializedName;
import java.util.Date;

@Entity(tableName = "movies") public class Movie implements Parcelable {
  @PrimaryKey // not autogenerated, use same ID as TheMovieDb.org
  private int id;
  private String title;
  private String overview;
  private boolean favorite = false;

  @SerializedName("poster_path") @ColumnInfo(name = "poster_path") private String posterPath;

  @SerializedName("vote_average") @ColumnInfo(name = "vote_average") private float voteAverage;

  @SerializedName("release_date") @ColumnInfo(name = "release_date") private Date releaseDate;

  // used by Room
  public Movie(int id, String title, String overview, String posterPath, float voteAverage,
      Date releaseDate, boolean favorite) {
    this.id = id;
    this.title = title;
    this.overview = overview;
    this.posterPath = posterPath;
    this.voteAverage = voteAverage;
    this.releaseDate = releaseDate;
    this.favorite = favorite;
  }

  @Ignore // Ignored by Room; used for Gson
  public Movie() {
  }

  @Ignore // Ignored by Room; used by Parcelables
  private Movie(Parcel parcel) {
    this.id = parcel.readInt();
    this.title = parcel.readString();
    this.overview = parcel.readString();
    this.posterPath = parcel.readString();
    this.voteAverage = parcel.readFloat();
    this.releaseDate = new Date(parcel.readLong());
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getPosterPath() {
    return posterPath;
  }

  public void setPosterPath(String posterPath) {
    this.posterPath = posterPath;
  }

  public String getOverview() {
    return overview;
  }

  public void setOverview(String overview) {
    this.overview = overview;
  }

  public float getVoteAverage() {
    return voteAverage;
  }

  public void setVoteAverage(float voteAverage) {
    this.voteAverage = voteAverage;
  }

  public Date getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(Date releaseDate) {
    this.releaseDate = releaseDate;
  }

  public boolean isFavorite() {
    return favorite;
  }

  public void setFavorite(boolean favorite) {
    this.favorite = favorite;
  }

  @Override public int describeContents() {
    return 0;
  }

  @Override public void writeToParcel(Parcel parcel, int i) {
    parcel.writeInt(this.id);
    parcel.writeString(this.title);
    parcel.writeString(this.overview);
    parcel.writeString(this.posterPath);
    parcel.writeFloat(this.voteAverage);
    parcel.writeLong(this.releaseDate.getTime());
  }

  // https://guides.codepath.com/android/using-parcelable
  public static final Parcelable.Creator<Movie> CREATOR = new Parcelable.Creator<Movie>() {
    @Override public Movie createFromParcel(Parcel parcel) {
      return new Movie(parcel);
    }

    @Override public Movie[] newArray(int i) {
      return new Movie[i];
    }
  };
}
